### ISSUE TITLE
zipAlignApk failed while running automation on multi devices simultaneously for app

### ISSUE THREAD

**Issue by sameer49** [sameer49/Appium-Grid-For-Android#1]
https://github.com/appium/appium/issues/4687

**Comment by droidniz** [comment]
if i used synchronized method for installing app i made and test script all devices get sequential manner running any another ways ?

**Comment by sameer49** [comment]
though you synchronized method, the apk file will be same.

**Comment by droidniz** [comment]
@sameer49 yes

**Comment by droidniz** [comment]
hi @sameer49 
while running in mac am getting this error but in windows is working fine 

java.io.IOException: Cannot run program "adb": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
    at java.lang.Runtime.exec(Runtime.java:617)
    at java.lang.Runtime.exec(Runtime.java:450)
    at java.lang.Runtime.exec(Runtime.java:347)
    at libs.CommandPrompt.runCommand(CommandPrompt.java:32)
    at libs.DeviceConfiguration.startADB(DeviceConfiguration.java:18)
    at libs.DeviceConfiguration.getDivces(DeviceConfiguration.java:43)
    at libs.BaseTest.<init>(BaseTest.java:31)
    at example.CalcExample.<init>(CalcExample.java:11)
    at example.CalcExample.main(CalcExample.java:46)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:184)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
    ... 9 more
class : class example.CalcExample
class : example.CalcExample
class : class example.CalcExample
methods: 17
methods: public void libs.BaseTest.start()
cons: public example.CalcExample(int)
deviceCount: 0

**Comment by sameer49** [comment]
For Mac download [Mac-Command-Setup.zip](https://github.com/sameer49/Appium-Grid-For-Android/blob/master/Mac-Command-Setup.zip?raw=true) unzip it, open terminal got to download location and run command sh Mac-Command-Setup.sh this will set adb and appium execuatbles into /usr/bin.

**Comment by santthoshkshar** [comment]
hi Sameer,

while executing code am facing below mentioned error

'appium' is not recognized as an internal or external command,
operable program or batch file.

please help on this how to reslove the issue

thanks in advance.....

**Comment by sameer49** [comment]
You might installed appium using nodejs
Please follow steps from readme

**Comment by sameer49** [comment]
You might not installed appium using nodejs
Follow steps on readme

**Comment by santthoshkshar** [comment]
am getting below error messages while installing and running appium 

1) Installing appium with cmd prompt
c:\users\santhosh.node-gyp\0.12.7\deps\v8\include\v8stdint.h(10): fatal error
C1083: Cannot open include file: 'stddef.h': No such file or directory [C:\User
s\Santhosh\AppData\Roaming\npm\node_modules\appium\node_modules\ws\node_modules
\utf-8-validate\build\validation.vcxproj]

2) executing script with gmail_example.jar through cmd file
C:\Appium>node.exe C:\Appium\node_modules\appium\bin\appium.js --address 127.0.0
.1 --port 5858 --udid 192.168.137.187:5555 --bootstrap-port 4545 --nodeconfig C:
\seleniumserver\andtest.json
←[33mwarn←[39m: Appium support for versions of node < 0.12 has been deprecated a
nd will be removed in a future version. Please upgrade!
←[36minfo←[39m: Welcome to Appium v1.4.0 (REV 8f63e2f91ef7907aed8bda763f4e5ca08e
86970a)
←[36minfo←[39m: Appium REST http interface listener started on 127.0.0.1:5858
←[36minfo←[39m: [debug] Non-default server args: {"udid":"192.168.137.187:5555",
"address":"127.0.0.1","port":5858,"bootstrapPort":4545,"nodeconfig":"C:\seleniu
mserver\andtest.json"}
←[36minfo←[39m: Console LogLevel: debug

org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new se
ssion. Possible causes are invalid address of the remote server or browser start
-up failure.
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:03:00'
System info: host: 'ML-SanthoshR-PC', ip: '10.10.50.62', os.name: 'Windows 7', o
s.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_40'
Driver info: driver.version: AndroidDriver
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.ja
va:593)
        at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriv
er.java:240)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.jav
a:126)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.jav
a:153)
        at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:109)
        at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java
:39)
        at libs.BaseTest.createDriver(BaseTest.java:57)
        at gmailTest.GmailExmaple.run(GmailExmaple.java:37)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:5
3261 [/127.0.0.1] failed: Connection refused: connect
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpCl
ientConnectionOperator.java:140)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(
PoolingHttpClientConnectionManager.java:318)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClie
ntExec.java:363)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.
java:219)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java
:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java
:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttp
Client.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
Client.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
Client.java:57)
        at org.openqa.selenium.remote.HttpCommandExecutor.fallBackExecute(HttpCo
mmandExecutor.java:215)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExe
cutor.java:184)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.ja
va:572)
        ... 9 more
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocke
t(PlainConnectionSocketFactory.java:72)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpCl
ientConnectionOperator.java:123)
        ... 21 more
java.lang.NullPointerException
        at gmailTest.GmailExmaple.login(GmailExmaple.java:19)
        at gmailTest.GmailExmaple.run(GmailExmaple.java:38)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-0" java.lang.NullPointerException
        at gmailTest.GmailExmaple.login(GmailExmaple.java:32)
        at gmailTest.GmailExmaple.run(GmailExmaple.java:38)
        at java.lang.Thread.run(Unknown Source)

**Comment by santthoshkshar** [comment]
if comment port = appiumMan.startAppium();  
Given port number and launched appium manually its working good

Could you plz help on this..

thanks in advance...

**Comment by Sabarinathan5** [comment]
While Running through Appium Grid in command Prompt, it shows as below. and  i am not getting anything

E:>java -jar calc_example.jar e:\AndroidCalculator.apk
adb service already started
Following device is connected
192.168.119.101:5555 generic GoogleNexus4-5.1.0 5.1

Following device is connected
G000H404540508AB Amazon KFFOWI 5.1.1

class : class calcTest.CalcExample
class : calcTest.CalcExample
class : class calcTest.CalcExample
methods: 17
methods: public void libs.BaseTest.start()
cons: public calcTest.CalcExample(int)
deviceCount: 2
appium --session-override -p 54789 --chromedriver-port 54791 -bp 54793
appium --session-override -p 54790 --chromedriver-port 54792 -bp 54794
